integration:
  apigee:
    enable-log: true
    uri: https://arquiteturaadmin-hml.autopasscorp.com/gerar-oauth-token/v2
    grant-type: client_credentials
    client-id: LxjFtW8JBhgrq63LoTkf0k8NygN9FOsX
    client-secret: TGz0qjGAe7MgGDUb
  keycloack:
    enable-log: true
    uri: https://homolog-keycloak.autopasscorp.com/auth/realms/{realm}/protocol/openid-connect/token
    uri-path-params:
       realm: MERCURY
    grant-type: password
    client-id: app-top
    client-secret: f6f2a0e6-ac5d-4c62-8561-1d7acd309b07